---
# This is the "Master Playbook"; it implements the Satis build.
# See http://docs.ansible.com/ansible/playbooks_best_practices.html#directory-layout for a description of the
# "Master Playbook"
- name: "development-node"
  hosts: all
  become: true
  become_user: "root"
  roles:
    # Visibility
    - "littlemanco.prometheus"
    - "juju4.osquery"
    # Identity
    - "development-node.yubikey"
    - "development-node.password-tools"
    # Virtualisation
    - "geerlingguy.docker"
    # Network Analysis
    - "development-node.network-tools"
    # Display
    - "development-node.xorg"
    - "development-node.terminal"
    # Language Support
    - "geerlingguy.php"
    # Package Management
    - "geerlingguy.composer"
    # Development Tooling
    - "development-node.linters"
    - "development-node.version-control"
    - "andrewrothstein.bazel"
    - "cmprescott.chrome"
    - "pixelart.phpstorm"
