---
- src: "https://github.com/geerlingguy/ansible-role-docker.git"
  version: "dd0c6e0"
  name: "geerlingguy.docker"
- src: "https://github.com/cmprescott/ansible-role-chrome.git"
  version: "4e936be"
  name: "cmprescott.chrome"
- src: "https://github.com/pixelart/ansible-role-phpstorm.git"
  version: "5e0c799"
  name: "pixelart.phpstorm"
- src: "https://github.com/littlemanco/ansible-role-prometheus"
  version: "f5dbc39"
  name: "littlemanco.prometheus"
- src: "https://github.com/juju4/ansible-osquery.git"
  version: "af825f6"
  name: "juju4.osquery"
- src: "https://github.com/andrewrothstein/ansible-bazel.git"
  version: "490b808"
  name: "andrewrothstein.bazel"
- src: "https://github.com/juju4/ansible-osquery.git"
  version: "e370237"
  name: "juju4.osquery"
- src: "https://github.com/geerlingguy/ansible-role-php.git"
  version: "2a45c42"
  name: "geerlingguy.php"
- src: "https://github.com/geerlingguy/ansible-role-composer.git"
  version: "7be8281"
  name: "geerlingguy.composer"
